### ISSUE TITLE
Collecting elements of `AsyncSequence` into a regular `Sequence`

### ISSUE THREAD

**Issue by tevelee** [apple/swift-async-algorithms#112]
Hi!

I'm thinking about the inverse operation of the [async](https://github.com/apple/swift-async-algorithms/blob/main/Guides/Lazy.md) property: a way to collect async elements into a synchronous sequence.

POC implementation (collecting into an `Array`):

```swift
extension AsyncSequence {
    public func collect() async rethrows -> [Element] {
        try await reduce(into: []) { $0.append($1) }
    }
}
```

It's probably a better idea to return a dedicated type that conforms to `Sequence`.

Or using the [recently pitched](https://github.com/apple/swift-evolution/blob/main/proposals/0346-light-weight-same-type-syntax.md) primary associated types:

```swift
extension AsyncSequence {
    public func collect() async rethrows -> some Sequence<Element> {
        try await reduce(into: .init()) { $0.append($1) }
    }
}
```

Do you think it's an equally important use-case?

**Comment by ABridoux** [comment]
In case of I think it might be [already implemented]5 https://github.com/apple/swift-async-algorithms/blob/main/Guides/Collections.md) through new initialisers on `RangeReplacableCollection`

**Comment by phausler** [comment]
This was definitely an alternative considered for those initializers: in the end we made the choice to use initializers on `SetAlgebra`,  `Dictionary` and `RangeReplaceableCollection` because that covered almost all the meaningfully interesting collections to collect into and it left the usage more like the heritage of `Sequence` than attempting to be full-on Rx. Given the choice between the two of following the standard library or following reactive design patterns - it feels more consistent (read Swifty) to take homage from the standard library.

**Comment by tevelee** [comment]
Thanks for the insight, it makes sense 👍
