### ISSUE TITLE
[Question] What is the point of having AsyncThrowingChannel parametrised with Failure ?

### ISSUE THREAD

**Issue by twittemb** [apple/swift-async-algorithms#129]
Hi everyone,

I don't understand why AsyncThrowingChannel is parametrised with a `Failure` type. This generic type is not exploited.

The `next()` function can throw any error anyway.
The `fail()` function is available only when the `Failure` is `Error`, which removes the need for a generic `Failure` type IMO.

we could have:

```
public func fail(_ error: any Error) async { ... }
```

or better, compiler-wise:

```
public func fail<ErrorType: Error>(_ error: ErrorType) async { ... }
```

Am I missing something here ?

Thanks.

**Comment by phausler** [comment]
Albeit that I tend to feel that there are only two kinds of `Error`: `Never` and `any Error`. That feeling is not shared among everyone - this mimics AsyncThrowingStream.

**Comment by twittemb** [comment]
Ok. But I still feel that having 2 types: 1 that cannot produce errors (`AsyncChannel`), and one that can (`AsyncThrowingChannel`), implies that the second one is not meant to handle `Never` otherwise there is no point in having an `AsyncChannel` type right? It is a bit like `Result` came in 2 flavours: `Result` and `ThrowingResult` ...

Anyway, I get the intent to mimic `AsyncThrowingStream`, but from what I can see there is no way to create an `AsyncThrowingStream` that uses a `Never` failure:

```swift
let asyncThrowingStream: AsyncThrowingStream<Int, Never> = AsyncThrowingStream { continuation in } // -> does not compile
let asyncThrowingChannel: AsyncThrowingChannel<Int, Never> = AsyncThrowingChannel() // does compile
```

Do you know why?

Other remark: Would accept a PR that uses `any Error` instead of `Error` in `AsyncThrowingChannel` ?

**Comment by phausler** [comment]
yea it might be interesting to see if we could somehow collapse the two types (`AsyncChannel` and `AsyncThrowingChannel`) down into one. The issue there is going to be the conformance to `AsyncSequence` and how that throws or not. Because if we collapse everything down then you have to either have a conditional conformance to `next` when it throws and one when it cannot (e.g. a failure type of Never). 

It is definitely worth investigation.

**Comment by twittemb** [comment]
I've tried to work on that today and I cannot figure out the proper way to do it. It meanly is because of the fact that it it not possible (to my knowledge) to create an `UnsafeContinuation` with a custom Error type.

Although `UnsafeContinuation` is parametrised by 2 types (Element and Error), we cannot use `withUnsafeThrowingContinuation()` to specify the error type. Currently there is no way in the standard library to have control on the error type of a Continuation.

To be able to merge `AsyncChannel` and `AsyncThrowingChannel` we need the `Failure` generic type to be used every where and have conditional function whether it is `Never` or not (to throw or not throw). The only blocker I have is this particular line:

```swift
  func next(_ generation: Int) async throws -> Element? {
    return try await withUnsafeThrowingContinuation { continuation in
```

because I need the continuation to be `UnsafeContinuation<Element?, Failure>`, and this is not possible.

IMO there is something wrong with the way `withUnsafeThrowingContinuation` does not provide a way to specify the error type. @phausler do you know why there is this limitation ?

thanks.

**Comment by phausler** [comment]
The reason for the continuation issue is because there is no typed throws in swift. So if `with*ThrowingContinuation` had a specific error type then it would be expected that the throwing type from the external `try await` on it would only throw that specific error type. Since that cannot be expressed I guess that the design for that (along with other such types) presumes only valid existing errors to be `any Error`. What might be possible as an alternative is to refactor it to use `UnsafeContinuation<Result<Success, Failure>, Never>` instead for the continuation type, but.... the problem is going to be that you cannot conditionally conform the iterator to `AsyncIteratorProtocol` twice, nor can you effectively conform it with a specialization where the failure is `Never`. Sadly those approaches just don't work. 

Long/short - from my exploration it seems like we just have to have two types because of that last point. Perhaps we should restrict creation of `AsyncThrowingChannel` to be only when `Failure` is `Error`. Similar to `AsyncThrowingStream`

**Comment by twittemb** [comment]
Thanks for your answer @phausler.

If we constraint `Failure` to `Error`, then I don't see the need for `Failure`. We can just have `any Error` everywhere in the code of `AsyncThrowingChannel`.

For instance in the standard library we have `AsyncThrowingMapSequence`. We know it can throw be it is not parametrised by a `Failure` type.

**Comment by phausler** [comment]
That is true; but there is a larger consideration hiding here...

The slightly larger/meta questions here start off with: does `AsyncSequence` itself, when adopted along w/ `AsyncIteratorProtocol` really have an implicit `Failure = any Error` when the iterator's `next` function is implemented as `throws`? And likewise if the `next` function is implemented as non throwing does that infer the implicit `Failure` type is `Never`?  The rub of course is when the throws method is dependent upon more than one source. We are missing union-types or union-generics; does a union of `Never` and `any Error` mean that it is `any Error`?
