### ISSUE TITLE
[Merge] Improve conception

### ISSUE THREAD

**Issue by twittemb** [apple/swift-async-algorithms#192]
Hi @phausler, I see an attempt of avoiding creating too much tasks and share Iterators between them in the merge algorithm https://github.com/apple/swift-async-algorithms/pull/185

Although it might work well, the resulting code is pretty complex.

I feel we could leverage async channels as a way of merging elements from several tasks that would consume the upstreams. It would simplify a lot the code. I have a working implementation on a branch that also handles rethrowing. I will open a PR tomorrow to suggest my implementation if you are willing to take a look.

thanks.

**Comment by FranzBusch** [comment]
Thanks for opening this. While I get your concern for simpler code the merge operator is a pretty complex piece.
The main motivation behind my PR is not only to reduce the number of tasks but also to remove the Sendable constraints on the iterator.

At the same time the new implementation is up to 3 times faster since it avoids spawning all these tasks.

Feel free to open a PR but I want to point out some of the requirements you need fulfill;
1. The Iterator must not be Sendable
2. Demand to the upstream must only be issued if the downstream requested an element
3. Cancellation to the upstream must be propagated when the downstream is cancelled
4. Rethrows must be supported

Happy to discuss more here or in the PR.

**Comment by twittemb** [comment]
Hi @FranzBusch 

thanks for those insights. From what I can tell, those requirements are fulfilled by the implementation I have in mind. I would appreciate if you could take a look a the PR I will published tomorrow.

thanks a lot.

**Comment by twittemb** [comment]
Hi @FranzBusch 

thanks for those insights. From what I can tell, those requirements are fulfilled by the implementation I have in mind. I would appreciate if you could take a look a the PR I will published tomorrow.

thanks a lot.

**Comment by twittemb** [comment]
@FranzBusch here is the PR https://github.com/apple/swift-async-algorithms/pull/193
It might need some tweaking and I will ensure the tests all pass repeatedly later today (they all pass individually).

The code is simpler for sure but I decided to reuse and compose AsyncMerge2Sequence in order to make the version with 3 params. I guess we also could do a specific Merge3StateMachine but not sure it worth it.

@phausler what do you think ?

**Comment by phausler** [comment]
I think merge and friends in the async-algorithms package are not per-se a goal to make them simple; instead we should focus on correctness and performance. Particularly the heap cost of AsyncChannel is probably going to be higher than the alternate approach. So in short I think that we should focus on first off correctness of behavior (which the Sendable requirement for merge is part of that), second we should then focus on task creation overhead (e.g. we should strive for eliminating per-element tasks). Then after those two are done we should focus on reducing heap overhead. And finally for perf we should strive to avoid lock contention. 

I think both of these approaches at a high level analysis meet the concept of correctness; which is great! And they (again at a 10000 meter view) reduce the per element task creation down to a per side based task creation which is also a distinct improvement. But as we look at potential heap impact and lock contention impact #193 has a slight advantage (at the cost of code complexity). 

I guess id rather us tackle the hard problems in the async-algos package so that users of this package don't need to.

**Comment by twittemb** [comment]
Hi to both of you. My intent was not to find at all cost a simpler solution. But if we can have something that is simple to understand, maintain, that is correct and performant enough, my point is that it is worth giving a shot, even if it means reusing established components.

you are right in the overhead induced by AsyncChannel and I’m working on a variation using AsyncStream that already seem to improve perf.

@FranzBusch from my point of view an AsyncStream is somehow the equivalent of all the mechanics you have to manage your internal buffer. I’m just trying to not reinvent it.

I will push un update tomorrow with the optimized code. If it still does meet our requirements then I will give up 😀.

Have a good one.

**Comment by FranzBusch** [comment]
I would argue the code that I wrote is simple since it contains a pretty straight forward state machine and all transitions can be easily seen by just reading over the switch. The only really complicated part is the setup of the task group. However, I understand that reusing something existing looks simpler.

While AsyncStream might be more performant even then you can't achieve the same level. Since every AsyncStream comes with a lock and a separate heap allocation for the buffer inside the stream.

**Comment by twittemb** [comment]
Hi there,

I've updated the PR and its description.

**Comment by twittemb** [comment]
The PR has been abandoned in favour of the better implementation of @FranzBusch performance wise. Thanks everyone for the nice discussions.
