### ISSUE TITLE
Build fails with macOS SDK on Xcode 14 RC (14A309) 

### ISSUE THREAD

**Issue by sinoru** [apple/swift-async-algorithms#195]
It does build fails on Xcode 14 RC (14A309)

I don't know which channel will be good for reports this issue, so I post it on here.
If this is not appropriate, please let me know.

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/1138433/189398955-a9a8b2aa-85db-4ce9-8f73-335b6cfcde5e.png">

**Comment by jshier** [comment]
Unfortunately Xcode 14.0 builds with Swift 5.7 on the 5.6 standard library, so we're going to run into issues like this until a better compilation condition is used. A possible fix would be to check for an actual macOS 13 framework rather than just Swift 5.7 but I'd hope Apple has a better suggestion.

**Comment by sinoru** [comment]
Might be it can be checked with `#if swift(>=5.7)`?

I though `#if swift(>=5.7)` for stdlib, and `#if compiler(>=5.7)` for compiler.

**Comment by MaxDesiatov** [comment]
Is this still relevant? I feel like this can be closed.
